import { createFileRoute } from "@tanstack/react-router";
import { useState, useEffect, useRef } from "react";
import { useStore } from "@/lib/store";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { toast } from "sonner";
import {
  Palette,
  Eye,
  Mail,
  ShieldAlert,
  FileText,
  RotateCcw,
  Sparkles,
  Save,
  Code2,
  Type,
  Copy,
  Info,
  CheckCircle2,
} from "lucide-react";
import type { EmailTemplateDefinition } from "@/lib/types";

export const Route = createFileRoute("/_authenticated/email-templates")({
  component: EmailTemplatesPage,
});

type TemplateKey =
  | "registration"
  | "approval"
  | "rejection"
  | "transaction"
  | "schedule"
  | "training"
  | "reset_password"
  | "reset_password_success";

interface TemplateMeta {
  key: TemplateKey;
  name: string;
  description: string;
  category: "Accounts" | "Activities" | "Security";
  subject: string;
  heading: string;
  message: string;
  buttonText?: string;
  autoComponentNote?: string;
  variables: string[];
}

const DEFAULT_TEMPLATES: Record<TemplateKey, TemplateMeta> = {
  registration: {
    key: "registration",
    name: "Registration Received",
    description: "Sent to newly registered members notifying them their account is pending review.",
    category: "Accounts",
    subject: "Account Registration Received",
    heading: "Registration Received",
    message: `Hello {name},

Thank you for registering your account with {app_name}.

Your registration details have been received and are currently awaiting review by the club administrator. You will receive another email notification once your account is reviewed.`,
    variables: ["name", "first_name", "email", "app_name", "portal_url"],
  },
  approval: {
    key: "approval",
    name: "Account Approved",
    description: "Sent to member when admin approves their registration request.",
    category: "Accounts",
    subject: "Your Account Has Been Approved!",
    heading: "Account Approved",
    message: `Hello {name},

Great news! Your account has been reviewed and approved by the club administrator.

You can now log in to the club portal and access the dashboard, book schedules, and join training sessions.`,
    buttonText: "Log In to Portal",
    autoComponentNote: "A styled action button linking directly to your portal is included automatically.",
    variables: ["name", "first_name", "email", "app_name", "portal_url"],
  },
  rejection: {
    key: "rejection",
    name: "Account Rejected",
    description: "Sent to applicant when admin declines their registration request.",
    category: "Accounts",
    subject: "Account Registration Status",
    heading: "Account Registration",
    message: `Hello {name},

Thank you for your interest. We regret to inform you that your registration request has been declined at this time.

If you have any questions or believe this was in error, please contact the club administrator.`,
    variables: ["name", "first_name", "email", "app_name", "portal_url"],
  },
  transaction: {
    key: "transaction",
    name: "Transaction Alert",
    description: "Sent to member when wallet credit recharge, debit, or refund is recorded.",
    category: "Accounts",
    subject: "New Account Transaction Alert",
    heading: "Transaction Alert",
    message: `Hello {name},

A new transaction has been recorded on your member account.`,
    autoComponentNote: "The transaction summary table (Description, Type, Amount, Balance) is automatically generated by the system below your message.",
    variables: ["name", "first_name", "description", "type", "amount", "balance", "currency", "app_name", "portal_url"],
  },
  schedule: {
    key: "schedule",
    name: "Play Schedule Notification",
    description: "Sent to accepted/invited members when play schedules are released or updated.",
    category: "Activities",
    subject: "Play Schedule Notification: {schedule_name}",
    heading: "{title}",
    message: `Hello {name},

The play schedule {schedule_name} has been {action_verb} by the club.`,
    autoComponentNote: "The schedule details table (Date, Location, Session Fee, Status) is automatically generated by the system below your message.",
    variables: ["name", "first_name", "schedule_name", "date", "location", "fee", "status", "title", "action_verb", "app_name", "portal_url"],
  },
  training: {
    key: "training",
    name: "Training Session Notification",
    description: "Sent to members when training programs are released or updated.",
    category: "Activities",
    subject: "Training Session Notification: {program_name}",
    heading: "{title}",
    message: `Hello {name},

The training course {program_name} has been {action_verb} by the club.`,
    autoComponentNote: "The training details table (Coach, Location, Dates, Status) is automatically generated by the system below your message.",
    variables: ["name", "first_name", "program_name", "coach", "location", "dates_html", "date_label", "status", "title", "action_verb", "app_name", "portal_url"],
  },
  reset_password: {
    key: "reset_password",
    name: "Password Reset Verification (OTP)",
    description: "Sent to users requesting a password reset with a 6-digit OTP code.",
    category: "Security",
    subject: "Password Reset Verification Code",
    heading: "Reset Password Request",
    message: `Hello {name},

We received a request to reset your password for your account.

Your 6-digit verification code (OTP) is:`,
    autoComponentNote: "The 6-digit verification code (OTP) box and expiration warning are automatically generated by the system below your message.",
    variables: ["name", "first_name", "otp", "app_name", "portal_url"],
  },
  reset_password_success: {
    key: "reset_password_success",
    name: "Password Reset Success",
    description: "Sent to users confirming their password was changed successfully.",
    category: "Security",
    subject: "Password Reset Successfully",
    heading: "Password Reset Successfully",
    message: `Hello {name},

Your password for your account has been successfully reset.

You can now sign in to your account using your new password.`,
    buttonText: "Sign In to Account",
    autoComponentNote: "A styled sign-in button and security notice are automatically generated by the system below your message.",
    variables: ["name", "first_name", "app_name", "portal_url"],
  },
};

export function compileTemplateHtml(
  key: TemplateKey,
  heading: string,
  message: string,
  buttonText?: string,
  primaryColor = "{primary_color}"
): string {
  const paragraphs = message
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => `<p style="margin: 12px 0; line-height: 1.6;">${p.replace(/\n/g, "<br/>")}</p>`)
    .join("\n");

  const headingColor =
    key === "rejection" ? "#EF4444" : key === "transaction" ? "{type_color}" : primaryColor;

  const headingHtml = heading
    ? `<h2 style="color: ${headingColor}; font-size: 18px; margin-top: 0; font-weight: bold;">${heading}</h2>\n`
    : "";

  let extraHtml = "";

  if (key === "approval") {
    const btn = buttonText || "Log In to Portal";
    extraHtml = `\n<div style="margin-top: 25px; text-align: center;">
    <a href="{portal_url}" style="display: inline-block; background-color: ${primaryColor}; color: #0C0F0E; font-weight: bold; text-decoration: none; padding: 10px 20px; border-radius: 4px;">${btn}</a>
</div>`;
  } else if (key === "transaction") {
    extraHtml = `\n<table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Description:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{description}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Type:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold; color: {type_color};">{type}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Amount:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{amount}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Account Balance:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{balance}</td>
    </tr>
</table>`;
  } else if (key === "schedule") {
    extraHtml = `\n<table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Date:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{date}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Location:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{location}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Session Fee:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{fee}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98;">Status:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold; text-transform: uppercase;">{status}</td>
    </tr>
</table>`;
  } else if (key === "training") {
    extraHtml = `\n<table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98; vertical-align: top;">Coach:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{coach}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98; vertical-align: top;">Location:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold;">{location}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98; vertical-align: top;">{date_label}</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06);">{dates_html}</td>
    </tr>
    <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); color: #8A9E98; vertical-align: top;">Status:</td>
        <td style="padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.06); font-weight: bold; text-transform: uppercase;">{status}</td>
    </tr>
</table>`;
  } else if (key === "reset_password") {
    extraHtml = `\n<div style="margin: 20px 0; text-align: center; background: rgba(255,255,255,0.03); padding: 16px; border-radius: 6px; border: 1px dashed ${primaryColor};">
    <span style="font-size: 28px; font-weight: bold; letter-spacing: 6px; color: ${primaryColor};">{otp}</span>
</div>
<p style="font-size: 12px; color: #8A9E98; margin-top: 15px;">This OTP code will expire in 15 minutes. If you did not request a password reset, please ignore this email.</p>`;
  } else if (key === "reset_password_success") {
    const btn = buttonText || "Sign In to Account";
    extraHtml = `\n<div style="margin-top: 25px; text-align: center;">
    <a href="{portal_url}" style="display: inline-block; background-color: ${primaryColor}; color: #0C0F0E; font-weight: bold; text-decoration: none; padding: 10px 20px; border-radius: 4px;">${btn}</a>
</div>
<p style="font-size: 12px; color: #8A9E98; margin-top: 20px;">If you did not perform this action, please contact the club administrator immediately.</p>`;
  }

  return `${headingHtml}${paragraphs}${extraHtml}`;
}

function interpolatePreview(
  text: string,
  key: TemplateKey,
  primaryColor: string,
  appName: string,
  currency: string
): string {
  if (!text) return "";
  const sampleVars: Record<string, string> = {
    name: "John Doe",
    first_name: "John",
    email: "john.doe@example.com",
    app_name: appName || "ClubConnect",
    portal_url: "#",
    primary_color: primaryColor,
    type_color: key === "transaction" ? "#EF4444" : primaryColor,
    description: "Play session: Monday Smash Arena",
    type: "Debited",
    amount: `${currency}15.00`,
    balance: `${currency}45.00`,
    currency: currency,
    schedule_name: "Monday Smash Arena",
    date: "2026-06-22",
    location: "Main Court A",
    fee: `${currency}15.00`,
    status: "RELEASED",
    title: key === "schedule" ? "New Schedule Released" : key === "training" ? "New Training Session Released" : "Notification",
    action_verb: "released",
    program_name: "Elite Junior Coaching",
    coach: "Coach Sarah Miller",
    date_label: "Start Date:",
    dates_html: "2026-06-25",
    otp: "849201",
  };

  let res = text;
  for (const [k, v] of Object.entries(sampleVars)) {
    res = res.replaceAll(`{${k}}`, v);
  }
  return res;
}

function EmailTemplatesPage() {
  const store = useStore();
  const updateSettings = store.updateSettings;
  const currentUser = store.currentUser;

  // Selected template
  const [selectedKey, setSelectedKey] = useState<TemplateKey>("transaction");

  // Editor mode: "text" (No Code, Simple Text) vs "html" (Advanced Raw HTML)
  const [editorMode, setEditorMode] = useState<"text" | "html">("text");

  // Local state for templates
  const [templates, setTemplates] = useState<Record<string, EmailTemplateDefinition>>(() => {
    const initial: Record<string, EmailTemplateDefinition> = {};
    for (const [k, meta] of Object.entries(DEFAULT_TEMPLATES)) {
      const serverTpl = store.emailTemplates?.[k];
      const heading = serverTpl?.heading ?? meta.heading;
      const message = serverTpl?.message ?? meta.message;
      const buttonText = serverTpl?.button_text ?? serverTpl?.buttonText ?? meta.buttonText;
      const body = serverTpl?.body ?? compileTemplateHtml(k as TemplateKey, heading, message, buttonText);

      initial[k] = {
        name: serverTpl?.name || meta.name,
        description: serverTpl?.description || meta.description,
        subject: serverTpl?.subject || meta.subject,
        heading,
        message,
        buttonText,
        button_text: buttonText,
        body,
        variables: serverTpl?.variables || meta.variables,
      };
    }
    return initial;
  });

  // Sync templates if store updates
  useEffect(() => {
    if (store.emailTemplates && Object.keys(store.emailTemplates).length > 0) {
      setTemplates((prev) => {
        const next = { ...prev };
        for (const [k, meta] of Object.entries(DEFAULT_TEMPLATES)) {
          const serverTpl = store.emailTemplates[k];
          if (serverTpl) {
            const heading = serverTpl.heading ?? meta.heading;
            const message = serverTpl.message ?? meta.message;
            const buttonText = serverTpl.button_text ?? serverTpl.buttonText ?? meta.buttonText;
            const body = serverTpl.body ?? compileTemplateHtml(k as TemplateKey, heading, message, buttonText);

            next[k] = {
              name: serverTpl.name || meta.name,
              description: serverTpl.description || meta.description,
              subject: serverTpl.subject || meta.subject,
              heading,
              message,
              buttonText,
              button_text: buttonText,
              body,
              variables: serverTpl.variables || meta.variables,
            };
          }
        }
        return next;
      });
    }
  }, [store.emailTemplates]);

  // Brand Styling states
  const [primaryColor, setPrimaryColor] = useState(store.emailPrimaryColor || "#10B981");
  const [bgColor, setBgColor] = useState(store.emailBgColor || "#0C0F0E");
  const [textColor, setTextColor] = useState(store.emailTextColor || "#E8F0EE");
  const [cardBgColor, setCardBgColor] = useState(store.emailCardBgColor || "#131916");
  const [footerText, setFooterText] = useState(store.emailFooterText || "");

  const [isSaving, setIsSaving] = useState(false);
  const messageTextareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    setPrimaryColor(store.emailPrimaryColor || "#10B981");
    setBgColor(store.emailBgColor || "#0C0F0E");
    setTextColor(store.emailTextColor || "#E8F0EE");
    setCardBgColor(store.emailCardBgColor || "#131916");
    setFooterText(store.emailFooterText || "");
  }, [
    store.emailPrimaryColor,
    store.emailBgColor,
    store.emailTextColor,
    store.emailCardBgColor,
    store.emailFooterText,
  ]);

  if (!currentUser || currentUser.role !== "admin") {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center space-y-4">
        <ShieldAlert className="size-16 text-red-500 animate-pulse" />
        <h2 className="text-xl font-bold text-[#F1F0EE]">Access Denied</h2>
        <p className="text-sm text-[#8A8A98] max-w-md">
          Only club administrators are authorized to access and modify outgoing email templates.
        </p>
      </div>
    );
  }

  const activeMeta = DEFAULT_TEMPLATES[selectedKey];
  const activeTemplate = templates[selectedKey] || {
    name: activeMeta.name,
    description: activeMeta.description,
    subject: activeMeta.subject,
    heading: activeMeta.heading,
    message: activeMeta.message,
    buttonText: activeMeta.buttonText,
    body: compileTemplateHtml(selectedKey, activeMeta.heading, activeMeta.message, activeMeta.buttonText),
    variables: activeMeta.variables,
  };

  const handleSubjectChange = (val: string) => {
    setTemplates((prev) => ({
      ...prev,
      [selectedKey]: {
        ...prev[selectedKey],
        subject: val,
      },
    }));
  };

  const handleHeadingChange = (val: string) => {
    const updatedHeading = val;
    const currentMsg = activeTemplate.message || "";
    const currentBtn = activeTemplate.buttonText || "";
    const compiled = compileTemplateHtml(selectedKey, updatedHeading, currentMsg, currentBtn);

    setTemplates((prev) => ({
      ...prev,
      [selectedKey]: {
        ...prev[selectedKey],
        heading: updatedHeading,
        body: compiled,
      },
    }));
  };

  const handleMessageChange = (val: string) => {
    const updatedMsg = val;
    const currentHeading = activeTemplate.heading || "";
    const currentBtn = activeTemplate.buttonText || "";
    const compiled = compileTemplateHtml(selectedKey, currentHeading, updatedMsg, currentBtn);

    setTemplates((prev) => ({
      ...prev,
      [selectedKey]: {
        ...prev[selectedKey],
        message: updatedMsg,
        body: compiled,
      },
    }));
  };

  const handleButtonTextChange = (val: string) => {
    const updatedBtn = val;
    const currentHeading = activeTemplate.heading || "";
    const currentMsg = activeTemplate.message || "";
    const compiled = compileTemplateHtml(selectedKey, currentHeading, currentMsg, updatedBtn);

    setTemplates((prev) => ({
      ...prev,
      [selectedKey]: {
        ...prev[selectedKey],
        buttonText: updatedBtn,
        button_text: updatedBtn,
        body: compiled,
      },
    }));
  };

  const handleRawBodyChange = (val: string) => {
    setTemplates((prev) => ({
      ...prev,
      [selectedKey]: {
        ...prev[selectedKey],
        body: val,
      },
    }));
  };

  const handleInsertVariable = (varName: string) => {
    const placeholder = `{${varName}}`;
    const textarea = messageTextareaRef.current;
    if (!textarea) {
      handleMessageChange((activeTemplate.message || "") + " " + placeholder);
      toast.info(`Inserted ${placeholder}`);
      return;
    }

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const current = activeTemplate.message || "";
    const updated = current.substring(0, start) + placeholder + current.substring(end);
    handleMessageChange(updated);

    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + placeholder.length, start + placeholder.length);
    }, 0);
    toast.info(`Inserted ${placeholder}`);
  };

  const handleResetCurrentTemplate = () => {
    const defaultTpl = DEFAULT_TEMPLATES[selectedKey];
    const compiled = compileTemplateHtml(selectedKey, defaultTpl.heading, defaultTpl.message, defaultTpl.buttonText);

    setTemplates((prev) => ({
      ...prev,
      [selectedKey]: {
        name: defaultTpl.name,
        description: defaultTpl.description,
        subject: defaultTpl.subject,
        heading: defaultTpl.heading,
        message: defaultTpl.message,
        buttonText: defaultTpl.buttonText,
        button_text: defaultTpl.buttonText,
        body: compiled,
        variables: defaultTpl.variables,
      },
    }));
    toast.info(`Reset "${defaultTpl.name}" to default text.`);
  };

  const handleResetBranding = () => {
    setPrimaryColor("#10B981");
    setBgColor("#0C0F0E");
    setTextColor("#E8F0EE");
    setCardBgColor("#131916");
    setFooterText(`© ${new Date().getFullYear()} ${store.appName || "ClubConnect"}. All rights reserved.`);
    toast.info("Reset branding options to system defaults.");
  };

  const handleSaveAll = async () => {
    setIsSaving(true);
    try {
      await updateSettings({
        emailTemplates: templates,
        emailPrimaryColor: primaryColor,
        emailBgColor: bgColor,
        emailTextColor: textColor,
        emailCardBgColor: cardBgColor,
        emailFooterText: footerText,
      });
      toast.success("All email templates saved successfully!");
    } catch (err: any) {
      toast.error(err.message || "Failed to save email templates");
    } finally {
      setIsSaving(false);
    }
  };

  // Preview content
  const previewSubject = interpolatePreview(
    activeTemplate.subject,
    selectedKey,
    primaryColor,
    store.appName || "ClubConnect",
    store.currency || "$"
  );

  const previewBodyHtml = interpolatePreview(
    activeTemplate.body || compileTemplateHtml(selectedKey, activeTemplate.heading || "", activeTemplate.message || "", activeTemplate.buttonText),
    selectedKey,
    primaryColor,
    store.appName || "ClubConnect",
    store.currency || "$"
  );

  const appLogoBase64 = store.appLogoBase64;
  const appLogoText = store.appLogoText;
  const appName = store.appName;

  return (
    <div className="space-y-6 pb-12">
      <PageHeader
        title="Email Templates & Notifications"
        description="Customize the subject, heading, message text, and branding colors for all 8 club notification emails."
        actions={
          <Button
            onClick={handleSaveAll}
            disabled={isSaving}
            className="btn-premium-solid h-9 px-5 font-semibold text-xs cursor-pointer rounded-lg flex items-center gap-2 shadow-lg shadow-primary/20"
          >
            <Save className="size-4" />
            {isSaving ? "Saving..." : "Save All Changes"}
          </Button>
        }
      />

      <Tabs defaultValue="templates" className="space-y-6">
        <TabsList className="bg-[#131916] border border-white/[0.06] p-1 h-10 rounded-xl">
          <TabsTrigger
            value="templates"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground text-xs font-semibold px-4 py-1.5 rounded-lg flex items-center gap-2 transition-all shadow-sm"
          >
            <FileText className="size-3.5" />
            Edit Template Text
          </TabsTrigger>
          <TabsTrigger
            value="branding"
            className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground text-xs font-semibold px-4 py-1.5 rounded-lg flex items-center gap-2 transition-all shadow-sm"
          >
            <Palette className="size-3.5" />
            Branding & Colors
          </TabsTrigger>
        </TabsList>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* Left Editor Column */}
          <div className="lg:col-span-6 space-y-6">
            <TabsContent value="templates" className="m-0 space-y-5">
              <Card className="bg-[#131916] border-[rgba(255,255,255,0.06)] signature-card-top shadow-xl">
                <CardHeader className="pb-3 border-b border-white/[0.03] flex flex-row items-center justify-between space-y-0">
                  <div>
                    <CardTitle className="text-xs font-semibold tracking-wider text-primary uppercase flex items-center gap-1.5">
                      <Mail className="size-4" /> Template Editor
                    </CardTitle>
                    <CardDescription className="text-[11px] text-muted-foreground mt-0.5">
                      Edit plain text without any HTML code tags.
                    </CardDescription>
                  </div>
                  <div className="flex items-center gap-2">
                    {/* Toggle between Text Only (default) and HTML Code */}
                    <div className="flex bg-[#1A2120] p-0.5 rounded-lg border border-white/[0.06]">
                      <button
                        type="button"
                        onClick={() => setEditorMode("text")}
                        className={`px-2 py-1 text-[10px] font-semibold rounded-md flex items-center gap-1 transition-colors cursor-pointer ${
                          editorMode === "text"
                            ? "bg-primary text-primary-foreground shadow-sm"
                            : "text-[#8A8A98] hover:text-white"
                        }`}
                      >
                        <Type className="size-3" />
                        Text Only
                      </button>
                      <button
                        type="button"
                        onClick={() => setEditorMode("html")}
                        className={`px-2 py-1 text-[10px] font-semibold rounded-md flex items-center gap-1 transition-colors cursor-pointer ${
                          editorMode === "html"
                            ? "bg-primary text-primary-foreground shadow-sm"
                            : "text-[#8A8A98] hover:text-white"
                        }`}
                      >
                        <Code2 className="size-3" />
                        HTML Code
                      </button>
                    </div>

                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleResetCurrentTemplate}
                      className="h-7 text-[11px] bg-[#1A2120] hover:bg-white/5 border-white/10 text-[#8A8A98] hover:text-white flex items-center gap-1.5 cursor-pointer rounded-md"
                    >
                      <RotateCcw className="size-3" /> Reset
                    </Button>
                  </div>
                </CardHeader>
                <CardContent className="pt-5 space-y-5">
                  {/* Template Dropdown */}
                  <div className="space-y-1.5">
                    <Label className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                      Select Email Template
                    </Label>
                    <Select
                      value={selectedKey}
                      onValueChange={(val) => setSelectedKey(val as TemplateKey)}
                    >
                      <SelectTrigger className="bg-[#1A2120] border-[rgba(255,255,255,0.08)] text-[#F1F0EE] h-10 text-xs font-medium cursor-pointer rounded-lg focus:border-primary">
                        <SelectValue placeholder="Select email template" />
                      </SelectTrigger>
                      <SelectContent className="bg-[#161C19] border-[rgba(255,255,255,0.12)] text-[#F1F0EE] max-h-80">
                        <div className="px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70">
                          Accounts & Members
                        </div>
                        <SelectItem value="registration" className="text-xs cursor-pointer hover:bg-white/5">
                          1. Registration Received
                        </SelectItem>
                        <SelectItem value="approval" className="text-xs cursor-pointer hover:bg-white/5">
                          2. Account Approved
                        </SelectItem>
                        <SelectItem value="rejection" className="text-xs cursor-pointer hover:bg-white/5">
                          3. Account Rejected
                        </SelectItem>
                        <SelectItem value="transaction" className="text-xs cursor-pointer hover:bg-white/5">
                          4. Transaction Alert (Credit/Debit/Refund)
                        </SelectItem>
                        <div className="px-2 py-1 mt-1.5 text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70 border-t border-white/[0.04]">
                          Club Activities
                        </div>
                        <SelectItem value="schedule" className="text-xs cursor-pointer hover:bg-white/5">
                          5. Play Schedule Notification
                        </SelectItem>
                        <SelectItem value="training" className="text-xs cursor-pointer hover:bg-white/5">
                          6. Training Session Notification
                        </SelectItem>
                        <div className="px-2 py-1 mt-1.5 text-[10px] font-bold uppercase tracking-wider text-muted-foreground/70 border-t border-white/[0.04]">
                          Security & Authentication
                        </div>
                        <SelectItem value="reset_password" className="text-xs cursor-pointer hover:bg-white/5">
                          7. Password Reset Verification (OTP)
                        </SelectItem>
                        <SelectItem value="reset_password_success" className="text-xs cursor-pointer hover:bg-white/5">
                          8. Password Reset Success
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <p className="text-[11px] text-muted-foreground flex items-center gap-1.5 pt-0.5">
                      <Info className="size-3 text-primary shrink-0" />
                      {activeTemplate.description}
                    </p>
                  </div>

                  {/* Email Subject Line */}
                  <div className="space-y-1.5">
                    <Label htmlFor="templateSubject" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider flex items-center justify-between">
                      <span>Email Subject</span>
                      <span className="text-[9px] lowercase font-mono text-muted-foreground">supports {"{variables}"}</span>
                    </Label>
                    <Input
                      id="templateSubject"
                      value={activeTemplate.subject}
                      onChange={(e) => handleSubjectChange(e.target.value)}
                      placeholder="e.g. New Account Transaction Alert"
                      className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-10 text-xs rounded-lg font-medium"
                    />
                  </div>

                  {/* TEXT ONLY MODE (Pure text without code tags) */}
                  {editorMode === "text" ? (
                    <>
                      {/* Email Heading Title */}
                      <div className="space-y-1.5">
                        <Label htmlFor="templateHeading" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                          Email Heading / Title Banner
                        </Label>
                        <Input
                          id="templateHeading"
                          value={activeTemplate.heading ?? activeMeta.heading}
                          onChange={(e) => handleHeadingChange(e.target.value)}
                          placeholder="e.g. Transaction Alert"
                          className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-10 text-xs rounded-lg font-medium"
                        />
                      </div>

                      {/* Message Content (Clean plain text) */}
                      <div className="space-y-1.5">
                        <div className="flex items-center justify-between">
                          <Label htmlFor="templateMessage" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                            Email Message (Plain Text)
                          </Label>
                          <span className="text-[10px] text-muted-foreground">
                            Use Enter key for new paragraphs
                          </span>
                        </div>
                        <Textarea
                          ref={messageTextareaRef}
                          id="templateMessage"
                          value={activeTemplate.message ?? activeMeta.message}
                          onChange={(e) => handleMessageChange(e.target.value)}
                          placeholder="Write your email message here..."
                          rows={6}
                          className="bg-[#1A2120] border-[rgba(255,255,255,0.08)] focus:border-primary text-[#F1F0EE] text-xs rounded-lg resize-y min-h-[140px] leading-relaxed"
                        />
                      </div>

                      {/* Button Text if applicable */}
                      {(selectedKey === "approval" || selectedKey === "reset_password_success") && (
                        <div className="space-y-1.5">
                          <Label htmlFor="templateButton" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                            Action Button Text
                          </Label>
                          <Input
                            id="templateButton"
                            value={activeTemplate.buttonText ?? activeMeta.buttonText ?? ""}
                            onChange={(e) => handleButtonTextChange(e.target.value)}
                            placeholder="e.g. Log In to Portal"
                            className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-10 text-xs rounded-lg font-medium"
                          />
                        </div>
                      )}

                      {/* Automated Component Notice (e.g. Table / OTP / Button) */}
                      {activeMeta.autoComponentNote && (
                        <div className="rounded-lg bg-primary/10 border border-primary/20 p-3 text-[11px] text-foreground flex items-center gap-2.5">
                          <CheckCircle2 className="size-4 text-primary shrink-0" />
                          <span>{activeMeta.autoComponentNote}</span>
                        </div>
                      )}
                    </>
                  ) : (
                    /* ADVANCED HTML CODE MODE */
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between">
                        <Label htmlFor="templateBodyRaw" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                          Raw Email HTML Content
                        </Label>
                        <span className="text-[10px] text-primary/80 font-mono">
                          {activeTemplate.body.length} chars
                        </span>
                      </div>
                      <Textarea
                        id="templateBodyRaw"
                        value={activeTemplate.body}
                        onChange={(e) => handleRawBodyChange(e.target.value)}
                        placeholder="Raw HTML code..."
                        rows={12}
                        className="bg-[#181F1D] border-[rgba(255,255,255,0.08)] focus:border-primary text-[#E8F0EE] font-mono text-xs rounded-lg resize-y min-h-[220px] leading-relaxed"
                      />
                    </div>
                  )}

                  {/* Available Dynamic Variables */}
                  <div className="space-y-2 pt-1 border-t border-white/[0.04]">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider flex items-center gap-1">
                        <Sparkles className="size-3 text-primary" />
                        Available Placeholders
                      </span>
                      <span className="text-[10px] text-muted-foreground">
                        Click chip to insert into message
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {activeTemplate.variables?.map((v) => (
                        <button
                          type="button"
                          key={v}
                          onClick={() => handleInsertVariable(v)}
                          title={`Click to insert {${v}}`}
                          className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-[#1D2523] hover:bg-[#25302D] border border-white/[0.06] hover:border-primary/40 text-[11px] font-mono text-primary transition-all cursor-pointer group active:scale-95"
                        >
                          <span>{`{${v}}`}</span>
                          <Copy className="size-2.5 opacity-40 group-hover:opacity-100 transition-opacity" />
                        </button>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="branding" className="m-0 space-y-5">
              <Card className="bg-[#131916] border-[rgba(255,255,255,0.06)] signature-card-top shadow-xl">
                <CardHeader className="pb-3 border-b border-white/[0.03] flex flex-row items-center justify-between space-y-0">
                  <div>
                    <CardTitle className="text-xs font-semibold tracking-wider text-primary uppercase flex items-center gap-1.5">
                      <Palette className="size-4" /> Global Email Styling
                    </CardTitle>
                    <CardDescription className="text-[11px] text-muted-foreground mt-0.5">
                      Define the visual colors and footer layout applied around all outgoing emails.
                    </CardDescription>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleResetBranding}
                    className="h-7 text-[11px] bg-[#1A2120] hover:bg-white/5 border-white/10 text-[#8A8A98] hover:text-white flex items-center gap-1.5 cursor-pointer rounded-md"
                  >
                    <RotateCcw className="size-3" /> Reset Defaults
                  </Button>
                </CardHeader>
                <CardContent className="pt-5 space-y-5">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label htmlFor="primaryColor" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                        Primary Accent
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          type="color"
                          id="primaryColorPicker"
                          value={primaryColor}
                          onChange={(e) => setPrimaryColor(e.target.value)}
                          className="w-10 h-9 p-0.5 border-0 rounded bg-[#1A2120] cursor-pointer"
                        />
                        <Input
                          type="text"
                          id="primaryColor"
                          maxLength={7}
                          value={primaryColor}
                          onChange={(e) => setPrimaryColor(e.target.value)}
                          className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-9 text-xs rounded-lg font-mono"
                        />
                      </div>
                    </div>

                    <div className="space-y-1.5">
                      <Label htmlFor="textColor" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                        Body Text Color
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          type="color"
                          id="textColorPicker"
                          value={textColor}
                          onChange={(e) => setTextColor(e.target.value)}
                          className="w-10 h-9 p-0.5 border-0 rounded bg-[#1A2120] cursor-pointer"
                        />
                        <Input
                          type="text"
                          id="textColor"
                          maxLength={7}
                          value={textColor}
                          onChange={(e) => setTextColor(e.target.value)}
                          className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-9 text-xs rounded-lg font-mono"
                        />
                      </div>
                    </div>

                    <div className="space-y-1.5">
                      <Label htmlFor="bgColor" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                        Email Outer Background
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          type="color"
                          id="bgColorPicker"
                          value={bgColor}
                          onChange={(e) => setBgColor(e.target.value)}
                          className="w-10 h-9 p-0.5 border-0 rounded bg-[#1A2120] cursor-pointer"
                        />
                        <Input
                          type="text"
                          id="bgColor"
                          maxLength={7}
                          value={bgColor}
                          onChange={(e) => setBgColor(e.target.value)}
                          className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-9 text-xs rounded-lg font-mono"
                        />
                      </div>
                    </div>

                    <div className="space-y-1.5">
                      <Label htmlFor="cardBgColor" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                        Email Inner Card Background
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          type="color"
                          id="cardBgColorPicker"
                          value={cardBgColor}
                          onChange={(e) => setCardBgColor(e.target.value)}
                          className="w-10 h-9 p-0.5 border-0 rounded bg-[#1A2120] cursor-pointer"
                        />
                        <Input
                          type="text"
                          id="cardBgColor"
                          maxLength={7}
                          value={cardBgColor}
                          onChange={(e) => setCardBgColor(e.target.value)}
                          className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] h-9 text-xs rounded-lg font-mono"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-1.5">
                    <Label htmlFor="footerText" className="text-[10px] font-semibold text-[#8A8A98] uppercase tracking-wider">
                      Footer Text / Copyright
                    </Label>
                    <Textarea
                      id="footerText"
                      value={footerText}
                      onChange={(e) => setFooterText(e.target.value)}
                      placeholder={`© ${new Date().getFullYear()} ${store.appName || "ClubConnect"}. All rights reserved.`}
                      rows={3}
                      className="bg-[#1A2120] border-[rgba(255,255,255,0.06)] focus:border-primary text-[#F1F0EE] text-xs rounded-lg resize-none leading-relaxed"
                    />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </div>

          {/* Right Column: Live Interactive Email Preview */}
          <div className="lg:col-span-6 sticky top-6">
            <Card className="bg-[#131916] border-[rgba(255,255,255,0.06)] signature-card-top shadow-2xl flex flex-col">
              <CardHeader className="pb-3 border-b border-white/[0.03] flex flex-row items-center justify-between space-y-0">
                <div className="space-y-0.5">
                  <div className="flex items-center gap-2">
                    <CardTitle className="text-xs font-semibold tracking-wider text-primary uppercase flex items-center gap-1.5">
                      <Eye className="size-4" /> Real-time Email Preview
                    </CardTitle>
                    <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-primary/10 text-primary border border-primary/20">
                      Live
                    </span>
                  </div>
                  <CardDescription className="text-[11px] text-muted-foreground">
                    Shows instant changes as you edit the subject, heading, text, or branding.
                  </CardDescription>
                </div>

                <div className="w-44 shrink-0">
                  <Select
                    value={selectedKey}
                    onValueChange={(val) => setSelectedKey(val as TemplateKey)}
                  >
                    <SelectTrigger className="bg-[#1A2120] border-[rgba(255,255,255,0.08)] text-[#F1F0EE] h-8 text-xs cursor-pointer rounded-lg">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-[#161C19] border-[rgba(255,255,255,0.12)] text-[#F1F0EE]">
                      <SelectItem value="registration" className="text-xs">Registration Received</SelectItem>
                      <SelectItem value="approval" className="text-xs">Account Approved</SelectItem>
                      <SelectItem value="rejection" className="text-xs">Account Rejected</SelectItem>
                      <SelectItem value="transaction" className="text-xs">Transaction Alert</SelectItem>
                      <SelectItem value="schedule" className="text-xs">Play Schedule</SelectItem>
                      <SelectItem value="training" className="text-xs">Training Session</SelectItem>
                      <SelectItem value="reset_password" className="text-xs">Reset Password OTP</SelectItem>
                      <SelectItem value="reset_password_success" className="text-xs">Reset Password Success</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </CardHeader>

              {/* Email Client Envelope Simulator */}
              <div className="p-4 bg-[#0A0D0C] rounded-b-xl space-y-3">
                {/* Email Client Header Bar */}
                <div className="bg-[#161C1A] border border-white/[0.06] rounded-lg p-3 space-y-1.5 text-xs">
                  <div className="flex items-center justify-between text-[11px]">
                    <span className="text-[#8A8A98]">From:</span>
                    <span className="text-[#F1F0EE] font-medium font-mono">
                      {store.mailFromName || store.appName || "ClubConnect"} &lt;{store.mailFromAddress || "noreply@club.com"}&gt;
                    </span>
                  </div>
                  <div className="flex items-center justify-between text-[11px] border-t border-white/[0.04] pt-1.5">
                    <span className="text-[#8A8A98]">Subject:</span>
                    <span className="text-primary font-semibold text-right truncate max-w-[320px]">
                      {previewSubject || "(No Subject)"}
                    </span>
                  </div>
                </div>

                {/* Email Content Frame */}
                <div
                  style={{
                    backgroundColor: bgColor,
                    color: textColor,
                    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
                    borderRadius: "8px",
                    padding: "24px 20px",
                    boxShadow: "0 10px 30px -10px rgba(0, 0, 0, 0.5)",
                    border: "1px solid rgba(255,255,255,0.04)",
                    transition: "all 0.15s ease-in-out",
                  }}
                >
                  {/* Brand Header */}
                  <div style={{ textAlign: "center", paddingBottom: "20px" }}>
                    {appLogoBase64 ? (
                      <img
                        src={appLogoBase64}
                        alt={appName || "ClubConnect"}
                        style={{ maxHeight: "38px", display: "block", margin: "0 auto" }}
                      />
                    ) : (
                      <div
                        style={{
                          display: "inline-block",
                          padding: "6px 14px",
                          backgroundColor: primaryColor,
                          color: "#000000",
                          fontWeight: "bold",
                          fontSize: "16px",
                          borderRadius: "4px",
                        }}
                      >
                        {appLogoText || "C"}
                      </div>
                    )}
                    <h1
                      style={{
                        fontSize: "18px",
                        marginTop: "10px",
                        marginBottom: "0",
                        fontWeight: "500",
                        color: textColor,
                      }}
                    >
                      {appName || "ClubConnect"}
                    </h1>
                  </div>

                  {/* Inner Card */}
                  <div
                    style={{
                      backgroundColor: cardBgColor,
                      border: "1px solid rgba(255, 255, 255, 0.06)",
                      borderRadius: "8px",
                      padding: "22px",
                      fontSize: "13px",
                      color: textColor,
                      lineHeight: "1.55",
                    }}
                    dangerouslySetInnerHTML={{ __html: previewBodyHtml }}
                  />

                  {/* Footer */}
                  <div
                    style={{
                      paddingTop: "22px",
                      textAlign: "center",
                      fontSize: "11px",
                      color: "#8A9E98",
                      lineHeight: "1.5",
                    }}
                  >
                    {footerText || `© ${new Date().getFullYear()} ${appName || "ClubConnect"}. All rights reserved.`}
                  </div>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </Tabs>
    </div>
  );
}
