/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTrainingsRouteImport } from './routes/_authenticated/trainings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedTrainingsNewRouteImport } from './routes/_authenticated/trainings.new'
import { Route as AuthenticatedTrainingsIdRouteImport } from './routes/_authenticated/trainings.$id'
import { Route as AuthenticatedSchedulesNewRouteImport } from './routes/_authenticated/schedules.new'
import { Route as AuthenticatedSchedulesIdRouteImport } from './routes/_authenticated/schedules.$id'
import { Route as AuthenticatedMembersAddRouteImport } from './routes/_authenticated/members.add'
import { Route as AuthenticatedTrainingsIdEditRouteImport } from './routes/_authenticated/trainings.$id.edit'
import { Route as AuthenticatedSchedulesIdEditRouteImport } from './routes/_authenticated/schedules.$id.edit'
import { Route as AuthenticatedMembersIdEditRouteImport } from './routes/_authenticated/members.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingsRoute = AuthenticatedTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingsNewRoute =
  AuthenticatedTrainingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTrainingsRoute,
  } as any)
const AuthenticatedTrainingsIdRoute =
  AuthenticatedTrainingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTrainingsRoute,
  } as any)
const AuthenticatedSchedulesNewRoute =
  AuthenticatedSchedulesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSchedulesRoute,
  } as any)
const AuthenticatedSchedulesIdRoute =
  AuthenticatedSchedulesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSchedulesRoute,
  } as any)
const AuthenticatedMembersAddRoute = AuthenticatedMembersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedMembersRoute,
} as any)
const AuthenticatedTrainingsIdEditRoute =
  AuthenticatedTrainingsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTrainingsIdRoute,
  } as any)
const AuthenticatedSchedulesIdEditRoute =
  AuthenticatedSchedulesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSchedulesIdRoute,
  } as any)
const AuthenticatedMembersIdEditRoute =
  AuthenticatedMembersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRouteWithChildren
  '/trainings': typeof AuthenticatedTrainingsRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/members/add': typeof AuthenticatedMembersAddRoute
  '/schedules/$id': typeof AuthenticatedSchedulesIdRouteWithChildren
  '/schedules/new': typeof AuthenticatedSchedulesNewRoute
  '/trainings/$id': typeof AuthenticatedTrainingsIdRouteWithChildren
  '/trainings/new': typeof AuthenticatedTrainingsNewRoute
  '/members/$id/edit': typeof AuthenticatedMembersIdEditRoute
  '/schedules/$id/edit': typeof AuthenticatedSchedulesIdEditRoute
  '/trainings/$id/edit': typeof AuthenticatedTrainingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/schedules': typeof AuthenticatedSchedulesRouteWithChildren
  '/trainings': typeof AuthenticatedTrainingsRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/members/add': typeof AuthenticatedMembersAddRoute
  '/schedules/$id': typeof AuthenticatedSchedulesIdRouteWithChildren
  '/schedules/new': typeof AuthenticatedSchedulesNewRoute
  '/trainings/$id': typeof AuthenticatedTrainingsIdRouteWithChildren
  '/trainings/new': typeof AuthenticatedTrainingsNewRoute
  '/members/$id/edit': typeof AuthenticatedMembersIdEditRoute
  '/schedules/$id/edit': typeof AuthenticatedSchedulesIdEditRoute
  '/trainings/$id/edit': typeof AuthenticatedTrainingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRouteWithChildren
  '/_authenticated/trainings': typeof AuthenticatedTrainingsRouteWithChildren
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/members/add': typeof AuthenticatedMembersAddRoute
  '/_authenticated/schedules/$id': typeof AuthenticatedSchedulesIdRouteWithChildren
  '/_authenticated/schedules/new': typeof AuthenticatedSchedulesNewRoute
  '/_authenticated/trainings/$id': typeof AuthenticatedTrainingsIdRouteWithChildren
  '/_authenticated/trainings/new': typeof AuthenticatedTrainingsNewRoute
  '/_authenticated/members/$id/edit': typeof AuthenticatedMembersIdEditRoute
  '/_authenticated/schedules/$id/edit': typeof AuthenticatedSchedulesIdEditRoute
  '/_authenticated/trainings/$id/edit': typeof AuthenticatedTrainingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/approvals'
    | '/credits'
    | '/dashboard'
    | '/invitations'
    | '/members'
    | '/profile'
    | '/schedules'
    | '/trainings'
    | '/transactions'
    | '/members/add'
    | '/schedules/$id'
    | '/schedules/new'
    | '/trainings/$id'
    | '/trainings/new'
    | '/members/$id/edit'
    | '/schedules/$id/edit'
    | '/trainings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/approvals'
    | '/credits'
    | '/dashboard'
    | '/invitations'
    | '/members'
    | '/profile'
    | '/schedules'
    | '/trainings'
    | '/transactions'
    | '/members/add'
    | '/schedules/$id'
    | '/schedules/new'
    | '/trainings/$id'
    | '/trainings/new'
    | '/members/$id/edit'
    | '/schedules/$id/edit'
    | '/trainings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/approvals'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/invitations'
    | '/_authenticated/members'
    | '/_authenticated/profile'
    | '/_authenticated/schedules'
    | '/_authenticated/trainings'
    | '/_authenticated/transactions'
    | '/_authenticated/members/add'
    | '/_authenticated/schedules/$id'
    | '/_authenticated/schedules/new'
    | '/_authenticated/trainings/$id'
    | '/_authenticated/trainings/new'
    | '/_authenticated/members/$id/edit'
    | '/_authenticated/schedules/$id/edit'
    | '/_authenticated/trainings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trainings': {
      id: '/_authenticated/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof AuthenticatedTrainingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trainings/new': {
      id: '/_authenticated/trainings/new'
      path: '/new'
      fullPath: '/trainings/new'
      preLoaderRoute: typeof AuthenticatedTrainingsNewRouteImport
      parentRoute: typeof AuthenticatedTrainingsRoute
    }
    '/_authenticated/trainings/$id': {
      id: '/_authenticated/trainings/$id'
      path: '/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof AuthenticatedTrainingsIdRouteImport
      parentRoute: typeof AuthenticatedTrainingsRoute
    }
    '/_authenticated/schedules/new': {
      id: '/_authenticated/schedules/new'
      path: '/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof AuthenticatedSchedulesNewRouteImport
      parentRoute: typeof AuthenticatedSchedulesRoute
    }
    '/_authenticated/schedules/$id': {
      id: '/_authenticated/schedules/$id'
      path: '/$id'
      fullPath: '/schedules/$id'
      preLoaderRoute: typeof AuthenticatedSchedulesIdRouteImport
      parentRoute: typeof AuthenticatedSchedulesRoute
    }
    '/_authenticated/members/add': {
      id: '/_authenticated/members/add'
      path: '/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof AuthenticatedMembersAddRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/trainings/$id/edit': {
      id: '/_authenticated/trainings/$id/edit'
      path: '/edit'
      fullPath: '/trainings/$id/edit'
      preLoaderRoute: typeof AuthenticatedTrainingsIdEditRouteImport
      parentRoute: typeof AuthenticatedTrainingsIdRoute
    }
    '/_authenticated/schedules/$id/edit': {
      id: '/_authenticated/schedules/$id/edit'
      path: '/edit'
      fullPath: '/schedules/$id/edit'
      preLoaderRoute: typeof AuthenticatedSchedulesIdEditRouteImport
      parentRoute: typeof AuthenticatedSchedulesIdRoute
    }
    '/_authenticated/members/$id/edit': {
      id: '/_authenticated/members/$id/edit'
      path: '/$id/edit'
      fullPath: '/members/$id/edit'
      preLoaderRoute: typeof AuthenticatedMembersIdEditRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
  }
}

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersAddRoute: typeof AuthenticatedMembersAddRoute
  AuthenticatedMembersIdEditRoute: typeof AuthenticatedMembersIdEditRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersAddRoute: AuthenticatedMembersAddRoute,
  AuthenticatedMembersIdEditRoute: AuthenticatedMembersIdEditRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedSchedulesIdRouteChildren {
  AuthenticatedSchedulesIdEditRoute: typeof AuthenticatedSchedulesIdEditRoute
}

const AuthenticatedSchedulesIdRouteChildren: AuthenticatedSchedulesIdRouteChildren =
  {
    AuthenticatedSchedulesIdEditRoute: AuthenticatedSchedulesIdEditRoute,
  }

const AuthenticatedSchedulesIdRouteWithChildren =
  AuthenticatedSchedulesIdRoute._addFileChildren(
    AuthenticatedSchedulesIdRouteChildren,
  )

interface AuthenticatedSchedulesRouteChildren {
  AuthenticatedSchedulesIdRoute: typeof AuthenticatedSchedulesIdRouteWithChildren
  AuthenticatedSchedulesNewRoute: typeof AuthenticatedSchedulesNewRoute
}

const AuthenticatedSchedulesRouteChildren: AuthenticatedSchedulesRouteChildren =
  {
    AuthenticatedSchedulesIdRoute: AuthenticatedSchedulesIdRouteWithChildren,
    AuthenticatedSchedulesNewRoute: AuthenticatedSchedulesNewRoute,
  }

const AuthenticatedSchedulesRouteWithChildren =
  AuthenticatedSchedulesRoute._addFileChildren(
    AuthenticatedSchedulesRouteChildren,
  )

interface AuthenticatedTrainingsIdRouteChildren {
  AuthenticatedTrainingsIdEditRoute: typeof AuthenticatedTrainingsIdEditRoute
}

const AuthenticatedTrainingsIdRouteChildren: AuthenticatedTrainingsIdRouteChildren =
  {
    AuthenticatedTrainingsIdEditRoute: AuthenticatedTrainingsIdEditRoute,
  }

const AuthenticatedTrainingsIdRouteWithChildren =
  AuthenticatedTrainingsIdRoute._addFileChildren(
    AuthenticatedTrainingsIdRouteChildren,
  )

interface AuthenticatedTrainingsRouteChildren {
  AuthenticatedTrainingsIdRoute: typeof AuthenticatedTrainingsIdRouteWithChildren
  AuthenticatedTrainingsNewRoute: typeof AuthenticatedTrainingsNewRoute
}

const AuthenticatedTrainingsRouteChildren: AuthenticatedTrainingsRouteChildren =
  {
    AuthenticatedTrainingsIdRoute: AuthenticatedTrainingsIdRouteWithChildren,
    AuthenticatedTrainingsNewRoute: AuthenticatedTrainingsNewRoute,
  }

const AuthenticatedTrainingsRouteWithChildren =
  AuthenticatedTrainingsRoute._addFileChildren(
    AuthenticatedTrainingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRouteWithChildren
  AuthenticatedTrainingsRoute: typeof AuthenticatedTrainingsRouteWithChildren
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRouteWithChildren,
  AuthenticatedTrainingsRoute: AuthenticatedTrainingsRouteWithChildren,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
